<?php /* Smarty version 2.6.18, created on 2009-09-29 15:06:26
         compiled from Dataface_Fineprint.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'translate', 'Dataface_Fineprint.html', 21, false),)), $this); ?>
<div class="fineprint">
<?php $this->_tag_stack[] = array('translate', array('id' => "templates.Dataface_Fineprint.POWERED_BY_WEBAUCTION")); $_block_repeat=true;$this->_plugins['block']['translate'][0][0]->translate($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Powered by <a href="http://webauction.weblite.ca">WebAuction</a><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo $this->_plugins['block']['translate'][0][0]->translate($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?><br/>
<?php $this->_tag_stack[] = array('translate', array('id' => "templates.Dataface_Fineprint.WEBAUCTION_DESIGNED_BY")); $_block_repeat=true;$this->_plugins['block']['translate'][0][0]->translate($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Developed by <a href="http://sjhannah.com">Steve Hannah</a> using <a href="http://data-face.com">Dataface</a>.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo $this->_plugins['block']['translate'][0][0]->translate($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?><br/>
<?php $this->_tag_stack[] = array('translate', array('id' => "templates.Dataface_Fineprint.WEBAUCTION_COPYRIGHT",'year' => "2005-2007")); $_block_repeat=true;$this->_plugins['block']['translate'][0][0]->translate($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>&copy; <a href="http://weblite.ca">Web Lite Solutions Corp.</a> 2005-2008 All rights reserved<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo $this->_plugins['block']['translate'][0][0]->translate($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>

</div>